layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
      - php-mysql-ajax
      - hotels-reservation-automation

  social_media:
    # website: https://erkanzileli.netlify.com
    # behance: your_username
    # dribbble: your_username
    # facebook: your_username
    # hackerrank: your_username
    # instagram: your_username
    # keybase: your_username
    linkedin: erkanzileli
    # mastodon: your_username
    medium: erkanzileli
    stackoverflow: 9183701
    # telegram: your_username
    # twitter: your_username
    # unsplash: your_username
    # vk: your_username
    # website: http://your_website_url
    # youtube: your_username

topics:
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png
